name: integration_tests

profile: integration_tests

version: '1.0'
config-version: 2
require-dbt-version: ">=1.0.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

vars:
  num2words_schema: common_schema

on-run-start:
  - >
    {{ dbt_translate.compile_money_to_words() }}