name: conitinous integration test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  integration-tests-sqlserver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sqlserver_version: ["2017", "2019", "2022"]
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-msft/dbt-sqlserver:server-${{ matrix.sqlserver_version }}
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install dbt-sqlserver

      - name: Copy profiles
        run: |
          mkdir -p ~/.dbt
          cp integration_tests/profiles/profiles.yml ~/.dbt/profiles.yml

      - name: Run integration test
        run: |
          dbt deps -t sqlserver
          dbt build -t sqlserver
        working-directory: integration_tests
        env:
          SQLSERVER_HOST: sqlserver
          SQLSERVER_PORT: 1433
          SQLSERVER_DATABASE: msdb
          SQLSERVER_USER: sa
          SQLSERVER_PASSWORD: 5atyaNadell@
          SQLSERVER_SCHEMA: PRCI_${{ github.sha }}